# Generated by Django 5.2 on 2025-06-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_tutor_about_me_remove_tutor_fee_per_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.tutor')),
            ],
            options={
                'ordering': ['tutor', 'start_time'],
                'unique_together': {('tutor', 'start_time', 'end_time')},
            },
        ),
    ]
