# Generated by Django 5.2 on 2025-05-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('fee_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='users.tutor')),
            ],
        ),
    ]
