# Generated by Django 5.2 on 2025-05-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_professionalprofile'),
    ]

    operations = [
    ]
