# Generated by Django 5.2 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_auto_20250507_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='fee_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
