# Generated by Django 5.2 on 2025-05-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='fee_per_hour',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='status',
        ),
    ]
