# Generated by Django 5.2 on 2025-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='fee_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
